---
address: 127.0.0.1
port: <%= 4999 + 1 %>
redis_address: 127.0.0.1
redis_port: 6379
redis_port: <%= case ENV["RACK_ENV"]
                when "test"
                  16379
                else
                  6379
                end
            %>
download_dir: Downloads
redis_dbfilename: <%= case ENV["RACK_ENV"]
                      when "test"
                        "test.rdb"
                      else
                        "dump.rdb"
                      end
                  %>
